-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- MATTHEW v38 - SPA
-- Entonces son–crucificados con él dos ladrones uno a derecha y uno a izquierda

BEGIN;
-- 4002703801: Τότε (G5119) → "Entonces"
WITH ep AS (INSERT INTO phrase (language_id, created_at) SELECT (SELECT id FROM language WHERE code = 'spa'), NOW() WHERE NOT EXISTS (SELECT 1 FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703801' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL) RETURNING id), epw AS (INSERT INTO phrase_word (phrase_id, word_id) SELECT id, '4002703801' FROM ep ON CONFLICT DO NOTHING) INSERT INTO gloss (phrase_id, gloss, state, updated_at, source) SELECT p.id, 'Entonces', 'UNAPPROVED', NOW(), 'IMPORT' FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703801' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL ON CONFLICT (phrase_id) DO UPDATE SET gloss = EXCLUDED.gloss, updated_at = EXCLUDED.updated_at WHERE gloss.gloss IS DISTINCT FROM EXCLUDED.gloss;
-- 4002703802: σταυροῦνται (G4717) → "son–crucificados"
WITH ep AS (INSERT INTO phrase (language_id, created_at) SELECT (SELECT id FROM language WHERE code = 'spa'), NOW() WHERE NOT EXISTS (SELECT 1 FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703802' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL) RETURNING id), epw AS (INSERT INTO phrase_word (phrase_id, word_id) SELECT id, '4002703802' FROM ep ON CONFLICT DO NOTHING) INSERT INTO gloss (phrase_id, gloss, state, updated_at, source) SELECT p.id, 'son–crucificados', 'UNAPPROVED', NOW(), 'IMPORT' FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703802' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL ON CONFLICT (phrase_id) DO UPDATE SET gloss = EXCLUDED.gloss, updated_at = EXCLUDED.updated_at WHERE gloss.gloss IS DISTINCT FROM EXCLUDED.gloss;
-- 4002703803: σὺν (G4862) → "con"
WITH ep AS (INSERT INTO phrase (language_id, created_at) SELECT (SELECT id FROM language WHERE code = 'spa'), NOW() WHERE NOT EXISTS (SELECT 1 FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703803' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL) RETURNING id), epw AS (INSERT INTO phrase_word (phrase_id, word_id) SELECT id, '4002703803' FROM ep ON CONFLICT DO NOTHING) INSERT INTO gloss (phrase_id, gloss, state, updated_at, source) SELECT p.id, 'con', 'UNAPPROVED', NOW(), 'IMPORT' FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703803' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL ON CONFLICT (phrase_id) DO UPDATE SET gloss = EXCLUDED.gloss, updated_at = EXCLUDED.updated_at WHERE gloss.gloss IS DISTINCT FROM EXCLUDED.gloss;
-- 4002703804: αὐτῷ (G0846) → "él"
WITH ep AS (INSERT INTO phrase (language_id, created_at) SELECT (SELECT id FROM language WHERE code = 'spa'), NOW() WHERE NOT EXISTS (SELECT 1 FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703804' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL) RETURNING id), epw AS (INSERT INTO phrase_word (phrase_id, word_id) SELECT id, '4002703804' FROM ep ON CONFLICT DO NOTHING) INSERT INTO gloss (phrase_id, gloss, state, updated_at, source) SELECT p.id, 'él', 'UNAPPROVED', NOW(), 'IMPORT' FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703804' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL ON CONFLICT (phrase_id) DO UPDATE SET gloss = EXCLUDED.gloss, updated_at = EXCLUDED.updated_at WHERE gloss.gloss IS DISTINCT FROM EXCLUDED.gloss;
-- 4002703805: δύο (G1417) → "dos"
WITH ep AS (INSERT INTO phrase (language_id, created_at) SELECT (SELECT id FROM language WHERE code = 'spa'), NOW() WHERE NOT EXISTS (SELECT 1 FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703805' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL) RETURNING id), epw AS (INSERT INTO phrase_word (phrase_id, word_id) SELECT id, '4002703805' FROM ep ON CONFLICT DO NOTHING) INSERT INTO gloss (phrase_id, gloss, state, updated_at, source) SELECT p.id, 'dos', 'UNAPPROVED', NOW(), 'IMPORT' FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703805' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL ON CONFLICT (phrase_id) DO UPDATE SET gloss = EXCLUDED.gloss, updated_at = EXCLUDED.updated_at WHERE gloss.gloss IS DISTINCT FROM EXCLUDED.gloss;
-- 4002703806: λῃσταί, (G3027) → "ladrones"
WITH ep AS (INSERT INTO phrase (language_id, created_at) SELECT (SELECT id FROM language WHERE code = 'spa'), NOW() WHERE NOT EXISTS (SELECT 1 FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703806' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL) RETURNING id), epw AS (INSERT INTO phrase_word (phrase_id, word_id) SELECT id, '4002703806' FROM ep ON CONFLICT DO NOTHING) INSERT INTO gloss (phrase_id, gloss, state, updated_at, source) SELECT p.id, 'ladrones', 'UNAPPROVED', NOW(), 'IMPORT' FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703806' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL ON CONFLICT (phrase_id) DO UPDATE SET gloss = EXCLUDED.gloss, updated_at = EXCLUDED.updated_at WHERE gloss.gloss IS DISTINCT FROM EXCLUDED.gloss;
-- 4002703807: εἷς (G1520) → "uno"
WITH ep AS (INSERT INTO phrase (language_id, created_at) SELECT (SELECT id FROM language WHERE code = 'spa'), NOW() WHERE NOT EXISTS (SELECT 1 FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703807' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL) RETURNING id), epw AS (INSERT INTO phrase_word (phrase_id, word_id) SELECT id, '4002703807' FROM ep ON CONFLICT DO NOTHING) INSERT INTO gloss (phrase_id, gloss, state, updated_at, source) SELECT p.id, 'uno', 'UNAPPROVED', NOW(), 'IMPORT' FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703807' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL ON CONFLICT (phrase_id) DO UPDATE SET gloss = EXCLUDED.gloss, updated_at = EXCLUDED.updated_at WHERE gloss.gloss IS DISTINCT FROM EXCLUDED.gloss;
-- 4002703808: ἐκ (G1537) → "a"
WITH ep AS (INSERT INTO phrase (language_id, created_at) SELECT (SELECT id FROM language WHERE code = 'spa'), NOW() WHERE NOT EXISTS (SELECT 1 FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703808' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL) RETURNING id), epw AS (INSERT INTO phrase_word (phrase_id, word_id) SELECT id, '4002703808' FROM ep ON CONFLICT DO NOTHING) INSERT INTO gloss (phrase_id, gloss, state, updated_at, source) SELECT p.id, 'a', 'UNAPPROVED', NOW(), 'IMPORT' FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703808' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL ON CONFLICT (phrase_id) DO UPDATE SET gloss = EXCLUDED.gloss, updated_at = EXCLUDED.updated_at WHERE gloss.gloss IS DISTINCT FROM EXCLUDED.gloss;
-- 4002703809: δεξιῶν, (G1188) → "derecha"
WITH ep AS (INSERT INTO phrase (language_id, created_at) SELECT (SELECT id FROM language WHERE code = 'spa'), NOW() WHERE NOT EXISTS (SELECT 1 FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703809' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL) RETURNING id), epw AS (INSERT INTO phrase_word (phrase_id, word_id) SELECT id, '4002703809' FROM ep ON CONFLICT DO NOTHING) INSERT INTO gloss (phrase_id, gloss, state, updated_at, source) SELECT p.id, 'derecha', 'UNAPPROVED', NOW(), 'IMPORT' FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703809' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL ON CONFLICT (phrase_id) DO UPDATE SET gloss = EXCLUDED.gloss, updated_at = EXCLUDED.updated_at WHERE gloss.gloss IS DISTINCT FROM EXCLUDED.gloss;
-- 4002703810: καὶ (G2532) → "y"
WITH ep AS (INSERT INTO phrase (language_id, created_at) SELECT (SELECT id FROM language WHERE code = 'spa'), NOW() WHERE NOT EXISTS (SELECT 1 FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703810' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL) RETURNING id), epw AS (INSERT INTO phrase_word (phrase_id, word_id) SELECT id, '4002703810' FROM ep ON CONFLICT DO NOTHING) INSERT INTO gloss (phrase_id, gloss, state, updated_at, source) SELECT p.id, 'y', 'UNAPPROVED', NOW(), 'IMPORT' FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703810' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL ON CONFLICT (phrase_id) DO UPDATE SET gloss = EXCLUDED.gloss, updated_at = EXCLUDED.updated_at WHERE gloss.gloss IS DISTINCT FROM EXCLUDED.gloss;
-- 4002703811: εἷς (G1520) → "uno"
WITH ep AS (INSERT INTO phrase (language_id, created_at) SELECT (SELECT id FROM language WHERE code = 'spa'), NOW() WHERE NOT EXISTS (SELECT 1 FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703811' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL) RETURNING id), epw AS (INSERT INTO phrase_word (phrase_id, word_id) SELECT id, '4002703811' FROM ep ON CONFLICT DO NOTHING) INSERT INTO gloss (phrase_id, gloss, state, updated_at, source) SELECT p.id, 'uno', 'UNAPPROVED', NOW(), 'IMPORT' FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703811' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL ON CONFLICT (phrase_id) DO UPDATE SET gloss = EXCLUDED.gloss, updated_at = EXCLUDED.updated_at WHERE gloss.gloss IS DISTINCT FROM EXCLUDED.gloss;
-- 4002703812: ἐξ (G1537) → "a"
WITH ep AS (INSERT INTO phrase (language_id, created_at) SELECT (SELECT id FROM language WHERE code = 'spa'), NOW() WHERE NOT EXISTS (SELECT 1 FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703812' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL) RETURNING id), epw AS (INSERT INTO phrase_word (phrase_id, word_id) SELECT id, '4002703812' FROM ep ON CONFLICT DO NOTHING) INSERT INTO gloss (phrase_id, gloss, state, updated_at, source) SELECT p.id, 'a', 'UNAPPROVED', NOW(), 'IMPORT' FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703812' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL ON CONFLICT (phrase_id) DO UPDATE SET gloss = EXCLUDED.gloss, updated_at = EXCLUDED.updated_at WHERE gloss.gloss IS DISTINCT FROM EXCLUDED.gloss;
-- 4002703813: εὐωνύμων. (G2176) → "izquierda"
WITH ep AS (INSERT INTO phrase (language_id, created_at) SELECT (SELECT id FROM language WHERE code = 'spa'), NOW() WHERE NOT EXISTS (SELECT 1 FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703813' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL) RETURNING id), epw AS (INSERT INTO phrase_word (phrase_id, word_id) SELECT id, '4002703813' FROM ep ON CONFLICT DO NOTHING) INSERT INTO gloss (phrase_id, gloss, state, updated_at, source) SELECT p.id, 'izquierda', 'UNAPPROVED', NOW(), 'IMPORT' FROM phrase p JOIN phrase_word pw ON pw.phrase_id = p.id WHERE pw.word_id = '4002703813' AND p.language_id = (SELECT id FROM language WHERE code = 'spa') AND p.deleted_at IS NULL ON CONFLICT (phrase_id) DO UPDATE SET gloss = EXCLUDED.gloss, updated_at = EXCLUDED.updated_at WHERE gloss.gloss IS DISTINCT FROM EXCLUDED.gloss;
COMMIT;
