-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Turkish (Türkçe) translation for 2 Samuel chapter 5
-- Generated by: opus-4.5-chirho
-- Language: tur

-- Idempotent INSERT for machine_gloss table
-- Uses ON CONFLICT DO UPDATE to handle existing entries

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500101', l.id, 've–geldiler', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500102', l.id, 'tüm', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500103', l.id, 'שִׁבְטֵ֧י', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500104', l.id, 'İsrail', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500105', l.id, 'El', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500106', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500107', l.id, 'חֶבְר֑וֹנָה', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500108', l.id, 've–dediler', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500109', l.id, 'diyerek', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500110', l.id, 'הִנְנ֛וּ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500111', l.id, 'עַצְמְךָ֥', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500112', l.id, 'וּֽבְשָׂרְךָ֖', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500113', l.id, 'biz', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500201', l.id, 'da', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500202', l.id, 'אֶתְמ֣וֹל', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500203', l.id, 'da', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500204', l.id, 'שִׁלְשׁ֗וֹם', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500205', l.id, 'בִּהְי֨וֹת', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500206', l.id, 'Şaul', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500207', l.id, 'kral', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500208', l.id, 'üzerimizde', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500209', l.id, 'sen', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500210', l.id, 'oldu', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500211', l.id, 'oldun', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500212', l.id, 'מוציא', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500213', l.id, 'çıkaran', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500214', l.id, 'והמבי', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500215', l.id, '(וְהַמֵּבִ֖יא)', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500216', l.id, 'sen', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500217', l.id, 'İsrail', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500218', l.id, 've–dedi', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500219', l.id, 'YHVH', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500220', l.id, 'sana', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500221', l.id, 'sen', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500222', l.id, 'תִרְעֶ֤ה', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500223', l.id, 'sen', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500224', l.id, 'halkım', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500225', l.id, 'sen', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500226', l.id, 'İsrail', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500227', l.id, 'וְאַתָּ֛ה', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500228', l.id, 'olacaksın', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500229', l.id, 'לְנָגִ֖יד', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500230', l.id, 'üzerinde', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500231', l.id, 'İsrail', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500301', l.id, 've–geldiler', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500302', l.id, 'tüm', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500303', l.id, 'yaşlıları', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500304', l.id, 'İsrail', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500305', l.id, 'El', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500306', l.id, 'kral', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500307', l.id, 'חֶבְר֔וֹנָה', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500308', l.id, 'וַיִּכְרֹ֣ת', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500309', l.id, 'onlara', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500310', l.id, 'kral', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500311', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500312', l.id, 'ahit', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500313', l.id, 'Hevron''da', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500314', l.id, 'önünde', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500315', l.id, 'YHVH', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500316', l.id, 'וַיִּמְשְׁח֧וּ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500317', l.id, 'sen', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500318', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500319', l.id, 'לְמֶ֖לֶךְ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500320', l.id, 'üzerinde', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500321', l.id, 'İsrail', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500401', l.id, 'oğul', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500402', l.id, 'otuz', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500403', l.id, 'yıl', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500404', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500405', l.id, 'בְּמָלְכ֑וֹ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500406', l.id, 'kırk', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500407', l.id, 'yıl', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500408', l.id, 'kral', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500501', l.id, 'Hevron''da', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500502', l.id, 'kral', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500503', l.id, 'üzerinde', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500504', l.id, 'Yehuda', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500505', l.id, 'yedi', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500506', l.id, 'iki', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500507', l.id, 'וְשִׁשָּׁ֣ה', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500508', l.id, 'aylar', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500509', l.id, 'וּבִירוּשָׁלִַ֣ם', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500510', l.id, 'kral', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500511', l.id, 'otuz', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500512', l.id, 'וְשָׁלֹשׁ֙', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500513', l.id, 'yıl', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500514', l.id, 'üzerinde', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500515', l.id, 'tüm', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500516', l.id, 'İsrail', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500517', l.id, 'וִיהוּדָֽה', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500601', l.id, 've–gitti', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500602', l.id, 'kral', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500603', l.id, 'וַֽאֲנָשָׁיו֙', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500604', l.id, 'Yeruşalayim', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500605', l.id, 'El', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500606', l.id, 'הַיְבֻסִ֖י', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500607', l.id, 'oturan', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500608', l.id, 'toprak', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500609', l.id, 've–dedi', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500610', l.id, 'Davut''a', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500611', l.id, 'diyerek', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500612', l.id, 'değil', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500613', l.id, 'geleceksin', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500614', l.id, 'işte', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500615', l.id, 'çünkü', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500616', l.id, 'anne', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500617', l.id, 'הֱסִֽירְךָ֗', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500618', l.id, 'הַעִוְרִ֤ים', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500619', l.id, 'וְהַפִּסְחִים֙', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500620', l.id, 'diyerek', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500621', l.id, 'değil', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500622', l.id, 'gelecek', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500623', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500624', l.id, 'işte', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500701', l.id, 'וַיִּלְכֹּ֣ד', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500702', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500703', l.id, 'sen', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500704', l.id, 'מְצֻדַ֣ת', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500705', l.id, 'צִיּ֑וֹן', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500706', l.id, 'o', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500707', l.id, 'şehir', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500708', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500801', l.id, 've–dedi', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500802', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500803', l.id, 'günde', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500804', l.id, 'הַה֗וּא', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500805', l.id, 'tüm', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500806', l.id, 'vuran', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500807', l.id, 'יְבֻסִי֙', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500808', l.id, 'וְיִגַּ֣ע', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500809', l.id, 'בַּצִּנּ֔וֹר', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500810', l.id, 'וְאֶת־', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500811', l.id, 'הַפִּסְחִים֙', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500812', l.id, 'וְאֶת־', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500813', l.id, 'הַ֣עִוְרִ֔ים', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500814', l.id, 'nefret–ettiler', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500815', l.id, '(שְׂנֻאֵ֖י)', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500816', l.id, 'can', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500817', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500818', l.id, 'üzerinde', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500819', l.id, 'böyle', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500820', l.id, 'diyecekler', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500821', l.id, 'עִוֵּ֣ר', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500822', l.id, 'וּפִסֵּ֔חַ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500823', l.id, 'değil', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500824', l.id, 'gelecek', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500825', l.id, 'El', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500826', l.id, 'ev', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500901', l.id, 've–döndü', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500902', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500903', l.id, 'בַּמְּצֻדָ֔ה', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500904', l.id, 've–çağırdı', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500905', l.id, 'ona', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500906', l.id, 'şehir', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500907', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500908', l.id, 've–inşa–etti', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500909', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500910', l.id, 'סָבִ֔יב', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500911', l.id, '–den', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500912', l.id, 'הַמִּלּ֖וֹא', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000500913', l.id, 'וָבָֽיְתָה', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501001', l.id, 've–gitti', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501002', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501003', l.id, 'הָל֣וֹךְ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501004', l.id, 'וְגָד֑וֹל', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501005', l.id, 'וַיהוָ֛ה', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501006', l.id, 'Elohim''i', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501007', l.id, 'Tsevaot', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501008', l.id, 'halkı', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501101', l.id, 've–gönderdi', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501102', l.id, 'חִירָ֨ם', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501103', l.id, 'kral', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501104', l.id, 'צֹ֥ר', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501105', l.id, 'מַלְאָכִים֮', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501106', l.id, 'El', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501107', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501108', l.id, 'וַעֲצֵ֣י', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501109', l.id, 'אֲרָזִ֔ים', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501110', l.id, 'וְחָרָשֵׁ֣י', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501111', l.id, 'ağaç', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501112', l.id, 'וְחָֽרָשֵׁ֖י', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501113', l.id, 'taş', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501114', l.id, 'קִ֑יר', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501115', l.id, 've–inşa–ettiler', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501116', l.id, 'ev', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501117', l.id, 'Davut''a', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501201', l.id, 've–bildi', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501202', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501203', l.id, 'çünkü', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501204', l.id, 'הֱכִינ֧וֹ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501205', l.id, 'YHVH', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501206', l.id, 'לְמֶ֖לֶךְ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501207', l.id, 'üzerinde', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501208', l.id, 'İsrail', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501209', l.id, 'וְכִי֙', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501210', l.id, 'kaldırdı', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501211', l.id, 'krallığı', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501212', l.id, 'için', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501213', l.id, 'halkı', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501214', l.id, 'İsrail', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501301', l.id, 've–aldı', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501302', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501303', l.id, 'hâlâ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501304', l.id, 'פִּֽלַגְשִׁ֤ים', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501305', l.id, 'וְנָשִׁים֙', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501306', l.id, 'מִיר֣וּשָׁלִַ֔ם', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501307', l.id, 'sonra', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501308', l.id, 'geldiler', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501309', l.id, 'Hevron''dan', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501310', l.id, 'וַיִּוָּ֥לְדּוּ‪‬', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501311', l.id, 'hâlâ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501312', l.id, 'Davut''a', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501313', l.id, 'oğullar', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501314', l.id, 'וּבָנֽוֹת', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501401', l.id, 'וְאֵ֗לֶּה', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501402', l.id, 'שְׁמ֛וֹת', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501403', l.id, 'הַיִּלֹּדִ֥ים', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501404', l.id, 'ona', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501405', l.id, 'בִּירוּשָׁלִָ֑ם', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501406', l.id, 'שַׁמּ֣וּעַ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501407', l.id, 'וְשׁוֹבָ֔ב', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501408', l.id, 've–verdi', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501409', l.id, 'וּשְׁלֹמֹֽה', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501501', l.id, 'וְיִבְחָ֥ר', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501502', l.id, 'וֶאֱלִישׁ֖וּעַ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501503', l.id, 'וְנֶ֥פֶג', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501504', l.id, 'וְיָפִֽיעַ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501601', l.id, 'וֶאֱלִישָׁמָ֥ע', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501602', l.id, 'וְאֶלְיָדָ֖ע', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501603', l.id, 'וֶאֱלִיפָֽלֶט', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501701', l.id, 've–duydular', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501702', l.id, 'Filistliler', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501703', l.id, 'çünkü', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501704', l.id, 'מָשְׁח֨וּ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501705', l.id, 'sen', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501706', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501707', l.id, 'לְמֶ֙לֶךְ֙', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501708', l.id, 'üzerinde', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501709', l.id, 'İsrail', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501710', l.id, 've–çıktılar', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501711', l.id, 'tüm', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501712', l.id, 'Filistliler', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501713', l.id, 'לְבַקֵּ֣שׁ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501714', l.id, 'sen', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501715', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501716', l.id, 've–duydu', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501717', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501718', l.id, 've–indi', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501719', l.id, 'El', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501720', l.id, 'הַמְּצוּדָֽה', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501801', l.id, 'וּפְלִשְׁתִּ֖ים', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501802', l.id, 'geldiler', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501803', l.id, 'וַיִּנָּטְשׁ֖וּ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501804', l.id, 'בְּעֵ֥מֶק', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501805', l.id, 'רְפָאִֽים', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501901', l.id, 've–sordu', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501902', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501903', l.id, 'YHVH''de', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501904', l.id, 'diyerek', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501905', l.id, 'הַאֶֽעֱלֶה֙', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501906', l.id, 'El', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501907', l.id, 'Filistliler', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501908', l.id, 'הֲתִתְּנֵ֖ם', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501909', l.id, 'elimde', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501910', l.id, 've–dedi', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501911', l.id, 'YHVH', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501912', l.id, 'El', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501913', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501914', l.id, 'çık', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501915', l.id, 'çünkü', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501916', l.id, 'Natan', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501917', l.id, 'אֶתֵּ֛ן', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501918', l.id, 'sen', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501919', l.id, 'Filistliler', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000501920', l.id, 'בְּיָדֶֽךָ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502001', l.id, 've–geldi', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502002', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502003', l.id, 'בְּבַֽעַל־פְּרָצִים֮', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502004', l.id, 've–vurdu–onları', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502005', l.id, 'isim', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502006', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502007', l.id, 've–dedi', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502008', l.id, 'פָּרַ֨ץ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502009', l.id, 'YHVH', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502010', l.id, 'sen', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502011', l.id, 'düşmanları', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502012', l.id, 'önünde', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502013', l.id, 'כְּפֶ֣רֶץ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502014', l.id, 'su', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502015', l.id, 'üzerinde', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502016', l.id, 'böyle', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502017', l.id, 'oku', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502018', l.id, 'isim', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502019', l.id, 'הַמָּק֥וֹם', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502020', l.id, 'הַה֖וּא', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502021', l.id, 'בַּ֥עַל פְּרָצִֽים', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502101', l.id, 'וַיַּעַזְבוּ־', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502102', l.id, 'isim', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502103', l.id, 'sen', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502104', l.id, 'עֲצַבֵּיהֶ֑ם', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502105', l.id, 'וַיִּשָּׂאֵ֥ם', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502106', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502107', l.id, 'וַאֲנָשָֽׁיו', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502201', l.id, 'וַיֹּסִ֥פוּ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502202', l.id, 'hâlâ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502203', l.id, 'Filistliler', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502204', l.id, 'לַֽעֲל֑וֹת', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502205', l.id, 'וַיִּנָּֽטְשׁ֖וּ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502206', l.id, 'בְּעֵ֥מֶק', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502207', l.id, 'רְפָאִֽים', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502301', l.id, 've–sordu', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502302', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502303', l.id, 'YHVH''de', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502304', l.id, 've–dedi', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502305', l.id, 'değil', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502306', l.id, 'çıkacaksın', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502307', l.id, 'הָסֵב֙', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502308', l.id, 'El', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502309', l.id, 'אַ֣חֲרֵיהֶ֔ם', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502310', l.id, 'וּבָ֥אתָ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502311', l.id, 'onlara', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502312', l.id, 'מִמּ֥וּל', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502313', l.id, 'בְּכָאִֽים', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502401', l.id, 've–oldu', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502402', l.id, 'בשמעך', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502403', l.id, '(כְּֽשָׁמְעֲךָ֞)', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502404', l.id, 'sen', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502405', l.id, 'ses', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502406', l.id, 'צְעָדָ֛ה', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502407', l.id, 'בְּרָאשֵׁ֥י', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502408', l.id, 'הַבְּכָאִ֖ים', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502409', l.id, 'אָ֣ז', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502410', l.id, 'תֶּחֱרָ֑ץ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502411', l.id, 'çünkü', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502412', l.id, 'אָ֗ז', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502413', l.id, 'çıkacak', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502414', l.id, 'YHVH', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502415', l.id, 'לְפָנֶ֔יךָ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502416', l.id, 'vurmak–için', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502417', l.id, 'בְּמַחֲנֵ֥ה', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502418', l.id, 'Filistliler', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502501', l.id, 've–yaptı', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502502', l.id, 'Davut', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502503', l.id, 'böyle', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502504', l.id, 'כַּאֲשֶׁ֥ר', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502505', l.id, 'צִוָּ֖הוּ', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502506', l.id, 'YHVH', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502507', l.id, 've–vurdu', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502508', l.id, 'sen', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502509', l.id, 'Filistliler', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502510', l.id, 'מִגֶּ֖בַע', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502511', l.id, 'kadar', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502512', l.id, 'בֹּאֲךָ֥', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")
SELECT '1000502513', l.id, 'גָֽזֶר', 'opus-4.5-chirho'
FROM "Language" l WHERE l.code = 'tur'
ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;
