-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58001014

-- οὐχὶ → ووخی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101401', l.id, 'ووخی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πάντες → سب
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101402', l.id, 'سب', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἰσὶν → ہیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101403', l.id, 'ہیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- λειτουργικὰ → لےیتوورگیکا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101404', l.id, 'لےیتوورگیکا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πνεύματα, → پنےوماتا،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101405', l.id, 'پنےوماتا،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἰς → کے–لیے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101406', l.id, 'کے–لیے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- διακονίαν → دیاکونیان
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101407', l.id, 'دیاکونیان', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀποστελλόμενα, → اپوستےللومےنا،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101408', l.id, 'اپوستےللومےنا،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- διὰ → ذریعے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101409', l.id, 'ذریعے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοὺς → –اُن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101410', l.id, '–اُن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μέλλοντας → مےللونتاس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101411', l.id, 'مےللونتاس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κληρονομεῖν → کلیرونومےین
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101412', l.id, 'کلیرونومےین', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- σωτηρίαν? → نجات؟
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101413', l.id, 'نجات؟', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

