-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58001011

-- αὐτοὶ → اوتوی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101101', l.id, 'اوتوی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀπολοῦνται; → اپولوونتای؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101102', l.id, 'اپولوونتای؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- σὺ → سو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101103', l.id, 'سو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δὲ → مگر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101104', l.id, 'مگر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- διαμένεις; → دیامےنےیس؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101105', l.id, 'دیامےنےیس؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101106', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πάντες → سب
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101107', l.id, 'سب', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὡς → جیسے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101108', l.id, 'جیسے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἱμάτιον → یماتیون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101109', l.id, 'یماتیون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- παλαιωθήσονται; → پالایوثیسونتای؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800101110', l.id, 'پالایوثیسونتای؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

