-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58002002

-- εἰ → اگر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200201', l.id, 'اگر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γὰρ → کیونکہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200202', l.id, 'کیونکہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὁ, → –یہ،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200203', l.id, '–یہ،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δι’ → دی’
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200204', l.id, 'دی’', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀγγέλων → –فرشتوں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200205', l.id, '–فرشتوں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- λαληθεὶς → لالیثےیس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200206', l.id, 'لالیثےیس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- λόγος, → کلام،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200207', l.id, 'کلام،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐγένετο → ہوا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200208', l.id, 'ہوا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- βέβαιος, → بےبایوس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200209', l.id, 'بےبایوس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200210', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πᾶσα → ہر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200211', l.id, 'ہر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- παράβασις → پاراباسیس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200212', l.id, 'پاراباسیس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200213', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- παρακοὴ → پاراکوی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200214', l.id, 'پاراکوی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔλαβεν → لیا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200215', l.id, 'لیا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔνδικον → ےندیکون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200216', l.id, 'ےندیکون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μισθαποδοσίαν, → میسثاپودوسیان،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200217', l.id, 'میسثاپودوسیان،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

