-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58002009

-- τὸν → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200901', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δὲ → مگر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200902', l.id, 'مگر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- βραχύ → براخو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200903', l.id, 'براخو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τι → تی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200904', l.id, 'تی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- παρ’ → پار’
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200905', l.id, 'پار’', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀγγέλους, → فرشتوں،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200906', l.id, 'فرشتوں،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἠλαττωμένον, → یلاتتومےنون،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200907', l.id, 'یلاتتومےنون،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- βλέπομεν, → دیکھتے–ہیں،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200908', l.id, 'دیکھتے–ہیں،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Ἰησοῦν, → یسوع،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200909', l.id, 'یسوع،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- διὰ → ذریعے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200910', l.id, 'ذریعے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὸ → –یہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200911', l.id, '–یہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πάθημα → پاثیما
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200912', l.id, 'پاثیما', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοῦ → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200913', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- θανάτου, → –موت،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200914', l.id, '–موت،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δόξῃ → –جلال
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200915', l.id, '–جلال', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200916', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τιμῇ → تیمی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200917', l.id, 'تیمی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐστεφανωμένον; → ےستےفانومےنون؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200918', l.id, 'ےستےفانومےنون؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὅπως → وپوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200919', l.id, 'وپوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- χάριτι → خاریتی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200920', l.id, 'خاریتی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Θεοῦ, → –خدا،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200921', l.id, '–خدا،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὑπὲρ → لیے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200922', l.id, 'لیے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- παντὸς → پانتوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200923', l.id, 'پانتوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γεύσηται → گےوسیتای
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200924', l.id, 'گےوسیتای', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- θανάτου. → –موت۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800200925', l.id, '–موت۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

