-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58002013

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201301', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πάλιν, → پھر،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201302', l.id, 'پھر،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Ἐγὼ → ےگو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201303', l.id, 'ےگو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔσομαι → ےسومای
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201304', l.id, 'ےسومای', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πεποιθὼς → پےپویثوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201305', l.id, 'پےپویثوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐπ’ → ےپ’
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201306', l.id, 'ےپ’', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αὐτῷ. → اُسے۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201307', l.id, 'اُسے۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201308', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πάλιν, → پھر،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201309', l.id, 'پھر،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Ἰδοὺ, → یدوو،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201310', l.id, 'یدوو،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐγὼ, → ےگو،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201311', l.id, 'ےگو،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201312', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὰ → –یہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201313', l.id, '–یہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- παιδία → پایدیا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201314', l.id, 'پایدیا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἅ → ا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201315', l.id, 'ا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μοι → موی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201316', l.id, 'موی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔδωκεν → دیا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201317', l.id, 'دیا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὁ → –یہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201318', l.id, '–یہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Θεός. → خدا۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201319', l.id, 'خدا۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

