-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58002018

-- ἐν → میں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201801', l.id, 'میں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ᾧ → جس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201802', l.id, 'جس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γὰρ → کیونکہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201803', l.id, 'کیونکہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πέπονθεν → پےپونثےن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201804', l.id, 'پےپونثےن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αὐτὸς, → اوتوس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201805', l.id, 'اوتوس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πειρασθείς, → پےیراسثےیس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201806', l.id, 'پےیراسثےیس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δύναται → سکتا–ہے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201807', l.id, 'سکتا–ہے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοῖς → –اُن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201808', l.id, '–اُن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πειραζομένοις → پےیرازومےنویس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201809', l.id, 'پےیرازومےنویس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- βοηθῆσαι. → بویثیسای۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800201810', l.id, 'بویثیسای۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

