-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58003016

-- τίνες → تینےس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800301601', l.id, 'تینےس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γὰρ → کیونکہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800301602', l.id, 'کیونکہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀκούσαντες → اکووسانتےس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800301603', l.id, 'اکووسانتےس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- παρεπίκραναν? → پارےپیکرانان؟
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800301604', l.id, 'پارےپیکرانان؟', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀλλ’ → الل’
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800301605', l.id, 'الل’', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὐ → نہیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800301606', l.id, 'نہیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πάντες → سب
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800301607', l.id, 'سب', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οἱ → –وہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800301608', l.id, '–وہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐξελθόντες → ےکسےلثونتےس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800301609', l.id, 'ےکسےلثونتےس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐξ → سے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800301610', l.id, 'سے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Αἰγύπτου → ایگوپتوو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800301611', l.id, 'ایگوپتوو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- διὰ → ذریعے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800301612', l.id, 'ذریعے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Μωϋσέως? → –موسیٰ؟
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800301613', l.id, '–موسیٰ؟', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

