-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58003009

-- οὗ → جس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800300901', l.id, 'جس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐπείρασαν → ےپےیراسان
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800300902', l.id, 'ےپےیراسان', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οἱ → –وہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800300903', l.id, '–وہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πατέρες → پاتےرےس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800300904', l.id, 'پاتےرےس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὑμῶν → تمہارے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800300905', l.id, 'تمہارے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐν → میں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800300906', l.id, 'میں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δοκιμασίᾳ, → دوکیماسی–،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800300907', l.id, 'دوکیماسی–،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800300908', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἶδον → ےیدون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800300909', l.id, 'ےیدون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὰ → –یہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800300910', l.id, '–یہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔργα → ےرگا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800300911', l.id, 'ےرگا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μου, → میرا،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800300912', l.id, 'میرا،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τεσσεράκοντα → تےسسےراکونتا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800300913', l.id, 'تےسسےراکونتا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔτη. → ےتی۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800300914', l.id, 'ےتی۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

