-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58004008

-- εἰ → اگر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800400801', l.id, 'اگر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γὰρ → کیونکہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800400802', l.id, 'کیونکہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αὐτοὺς → اُن–کو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800400803', l.id, 'اُن–کو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Ἰησοῦς → یسوع
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800400804', l.id, 'یسوع', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κατέπαυσεν, → کاتےپاوسےن،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800400805', l.id, 'کاتےپاوسےن،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὐκ → نہیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800400806', l.id, 'نہیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἂν → ان
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800400807', l.id, 'ان', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- περὶ → بارے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800400808', l.id, 'بارے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἄλλης → اللیس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800400809', l.id, 'اللیس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐλάλει, → ےلالےی،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800400810', l.id, 'ےلالےی،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μετὰ → ساتھ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800400811', l.id, 'ساتھ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ταῦτα → یہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800400812', l.id, 'یہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἡμέρας. → –دن۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800400813', l.id, '–دن۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

