-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58005009

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500901', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τελειωθεὶς, → تےلےیوثےیس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500902', l.id, 'تےلےیوثےیس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐγένετο → ہوا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500903', l.id, 'ہوا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πᾶσιν, → سب–کو،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500904', l.id, 'سب–کو،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοῖς → –اُن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500905', l.id, '–اُن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὑπακούουσιν → وپاکووووسین
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500906', l.id, 'وپاکووووسین', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αὐτῷ, → اُسے،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500907', l.id, 'اُسے،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αἴτιος → ایتیوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500908', l.id, 'ایتیوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- σωτηρίας → –نجات
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500909', l.id, '–نجات', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αἰωνίου; → –ابدی؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500910', l.id, '–ابدی؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

