-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58005007

-- ὃς → جو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500701', l.id, 'جو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐν → میں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500702', l.id, 'میں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ταῖς → تایس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500703', l.id, 'تایس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἡμέραις → یمےرایس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500704', l.id, 'یمےرایس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῆς → –کی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500705', l.id, '–کی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- σαρκὸς → سارکوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500706', l.id, 'سارکوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αὐτοῦ, → اُس–کا،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500707', l.id, 'اُس–کا،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δεήσεις → دےیسےیس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500708', l.id, 'دےیسےیس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τε → تے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500709', l.id, 'تے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500710', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἱκετηρίας, → یکےتیریاس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500711', l.id, 'یکےتیریاس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πρὸς → کے–لیے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500712', l.id, 'کے–لیے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὸν → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500713', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δυνάμενον → دونامےنون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500714', l.id, 'دونامےنون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- σῴζειν → س–زےین
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500715', l.id, 'س–زےین', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αὐτὸν → اوتون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500716', l.id, 'اوتون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐκ → سے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500717', l.id, 'سے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- θανάτου, → –موت،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500718', l.id, '–موت،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μετὰ → ساتھ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500719', l.id, 'ساتھ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κραυγῆς → کراوگیس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500720', l.id, 'کراوگیس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἰσχυρᾶς → یسخوراس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500721', l.id, 'یسخوراس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500722', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δακρύων → داکروون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500723', l.id, 'داکروون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- προσενέγκας, → پروسےنےگکاس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500724', l.id, 'پروسےنےگکاس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500725', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἰσακουσθεὶς, → ےیساکووسثےیس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500726', l.id, 'ےیساکووسثےیس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀπὸ → سے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500727', l.id, 'سے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῆς → –کی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500728', l.id, '–کی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εὐλαβείας. → ےولابےیاس۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800500729', l.id, 'ےولابےیاس۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

