-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58006007

-- γῆ → زمین
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600701', l.id, 'زمین', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γὰρ → کیونکہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600702', l.id, 'کیونکہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἡ → –یہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600703', l.id, '–یہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πιοῦσα → پیووسا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600704', l.id, 'پیووسا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὸν, → –اُس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600705', l.id, '–اُس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐπ’ → ےپ’
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600706', l.id, 'ےپ’', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αὐτῆς → اُس–کی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600707', l.id, 'اُس–کی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐρχόμενον → آنے–والا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600708', l.id, 'آنے–والا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πολλάκις, → پوللاکیس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600709', l.id, 'پوللاکیس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὑετόν, → وےتون،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600710', l.id, 'وےتون،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600711', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τίκτουσα → تیکتووسا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600712', l.id, 'تیکتووسا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- βοτάνην → بوتانین
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600713', l.id, 'بوتانین', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εὔθετον → ےوثےتون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600714', l.id, 'ےوثےتون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐκείνοις → ےکےینویس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600715', l.id, 'ےکےینویس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δι’ → دی’
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600716', l.id, 'دی’', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὓς → ووس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600717', l.id, 'ووس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600718', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γεωργεῖται, → گےورگےیتای،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600719', l.id, 'گےورگےیتای،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μεταλαμβάνει → مےتالامبانےی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600720', l.id, 'مےتالامبانےی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εὐλογίας → ےولوگیاس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600721', l.id, 'ےولوگیاس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀπὸ → سے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600722', l.id, 'سے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοῦ → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600723', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Θεοῦ; → –خدا؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600724', l.id, '–خدا؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

