-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58006020

-- ὅπου → وپوو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800602001', l.id, 'وپوو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πρόδρομος → پرودروموس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800602002', l.id, 'پرودروموس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὑπὲρ → لیے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800602003', l.id, 'لیے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἡμῶν, → ہمارے،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800602004', l.id, 'ہمارے،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἰσῆλθεν → ےیسیلثےن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800602005', l.id, 'ےیسیلثےن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Ἰησοῦς, → یسوع،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800602006', l.id, 'یسوع،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κατὰ → مطابق
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800602007', l.id, 'مطابق', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὴν → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800602008', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τάξιν → تاکسین
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800602009', l.id, 'تاکسین', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Μελχισέδεκ, → ملک–صدق،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800602010', l.id, 'ملک–صدق،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀρχιερεὺς → ارخیےرےوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800602011', l.id, 'ارخیےرےوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γενόμενος → ہو–کر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800602012', l.id, 'ہو–کر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἰς → کے–لیے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800602013', l.id, 'کے–لیے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὸν → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800602014', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αἰῶνα. → ایونا۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800602015', l.id, 'ایونا۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

