-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58006002

-- βαπτισμῶν → باپتیسمون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600201', l.id, 'باپتیسمون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- διδαχὴν, → دیداخین،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600202', l.id, 'دیداخین،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐπιθέσεώς → ےپیثےسےوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600203', l.id, 'ےپیثےسےوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τε → تے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600204', l.id, 'تے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- χειρῶν, → خےیرون،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600205', l.id, 'خےیرون،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀναστάσεώς → اناستاسےوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600206', l.id, 'اناستاسےوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ‹τε› → ‹تے›
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600207', l.id, '‹تے›', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- νεκρῶν, → نےکرون،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600208', l.id, 'نےکرون،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600209', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κρίματος → کریماتوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600210', l.id, 'کریماتوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αἰωνίου; → –ابدی؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600211', l.id, '–ابدی؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

