-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58006010

-- οὐ → نہیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601001', l.id, 'نہیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γὰρ → کیونکہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601002', l.id, 'کیونکہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἄδικος → ادیکوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601003', l.id, 'ادیکوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὁ → –یہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601004', l.id, '–یہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Θεὸς, → خدا،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601005', l.id, 'خدا،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐπιλαθέσθαι → ےپیلاثےسثای
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601006', l.id, 'ےپیلاثےسثای', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοῦ → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601007', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔργου → ےرگوو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601008', l.id, 'ےرگوو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὑμῶν, → تمہارے،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601009', l.id, 'تمہارے،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601010', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῆς → –کی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601011', l.id, '–کی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀγάπης → –محبت
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601012', l.id, '–محبت', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἧς → جس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601013', l.id, 'جس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐνεδείξασθε → ےنےدےیکساسثے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601014', l.id, 'ےنےدےیکساسثے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἰς → کے–لیے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601015', l.id, 'کے–لیے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὸ → –یہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601016', l.id, '–یہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὄνομα → نام
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601017', l.id, 'نام', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αὐτοῦ, → اُس–کا،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601018', l.id, 'اُس–کا،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- διακονήσαντες → دیاکونیسانتےس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601019', l.id, 'دیاکونیسانتےس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοῖς → –اُن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601020', l.id, '–اُن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἁγίοις, → مقدسوں،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601021', l.id, 'مقدسوں،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601022', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- διακονοῦντες. → دیاکونوونتےس۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800601023', l.id, 'دیاکونوونتےس۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

