-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58006009

-- Πεπείσμεθα → پےپےیسمےثا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600901', l.id, 'پےپےیسمےثا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δὲ → مگر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600902', l.id, 'مگر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- περὶ → بارے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600903', l.id, 'بارے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὑμῶν, → تمہارے،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600904', l.id, 'تمہارے،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀγαπητοί, → اگاپیتوی،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600905', l.id, 'اگاپیتوی،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὰ → –یہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600906', l.id, '–یہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κρείσσονα, → کرےیسسونا،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600907', l.id, 'کرےیسسونا،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600908', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐχόμενα → ےخومےنا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600909', l.id, 'ےخومےنا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- σωτηρίας, → –نجات،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600910', l.id, '–نجات،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἰ → اگر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600911', l.id, 'اگر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600912', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὕτως → اِسی–طرح
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600913', l.id, 'اِسی–طرح', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- λαλοῦμεν. → لالوومےن۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800600914', l.id, 'لالوومےن۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

