-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58007027

-- ὃς → جو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702701', l.id, 'جو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὐκ → نہیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702702', l.id, 'نہیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔχει → رکھتا–ہے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702703', l.id, 'رکھتا–ہے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καθ’ → کاث’
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702704', l.id, 'کاث’', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἡμέραν → یمےران
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702705', l.id, 'یمےران', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀνάγκην, → اناگکین،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702706', l.id, 'اناگکین،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὥσπερ → جس–طرح
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702707', l.id, 'جس–طرح', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οἱ → –وہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702708', l.id, '–وہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀρχιερεῖς, → سردار–کاہن،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702709', l.id, 'سردار–کاہن،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πρότερον → پروتےرون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702710', l.id, 'پروتےرون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὑπὲρ → لیے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702711', l.id, 'لیے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῶν → –کے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702712', l.id, '–کے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἰδίων → یدیون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702713', l.id, 'یدیون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἁμαρτιῶν, → –گناہوں،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702714', l.id, '–گناہوں،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- θυσίας → –قربانی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702715', l.id, '–قربانی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀναφέρειν, → انافےرےین،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702716', l.id, 'انافےرےین،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔπειτα → ےپےیتا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702717', l.id, 'ےپےیتا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῶν → –کے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702718', l.id, '–کے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοῦ → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702719', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- λαοῦ; → –قوم؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702720', l.id, '–قوم؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοῦτο → یہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702721', l.id, 'یہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γὰρ → کیونکہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702722', l.id, 'کیونکہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐποίησεν → کیا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702723', l.id, 'کیا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐφάπαξ, → ےفاپاکس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702724', l.id, 'ےفاپاکس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἑαυτὸν → ےاوتون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702725', l.id, 'ےاوتون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀνενέγκας. → انےنےگکاس۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702726', l.id, 'انےنےگکاس۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

