-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58007002

-- ᾧ → جس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700201', l.id, 'جس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700202', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δεκάτην → دےکاتین
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700203', l.id, 'دےکاتین', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀπὸ → سے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700204', l.id, 'سے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πάντων → –سب
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700205', l.id, '–سب', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐμέρισεν → ےمےریسےن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700206', l.id, 'ےمےریسےن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Ἀβραάμ. → ابراہام۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700207', l.id, 'ابراہام۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πρῶτον → پہلے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700208', l.id, 'پہلے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μὲν → مےن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700209', l.id, 'مےن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἑρμηνευόμενος, → ےرمینےوومےنوس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700210', l.id, 'ےرمینےوومےنوس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- βασιλεὺς → باسیلےوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700211', l.id, 'باسیلےوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δικαιοσύνης, → –راستبازی،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700212', l.id, '–راستبازی،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔπειτα → ےپےیتا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700213', l.id, 'ےپےیتا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δὲ → مگر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700214', l.id, 'مگر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ, → اور،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700215', l.id, 'اور،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- βασιλεὺς → باسیلےوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700216', l.id, 'باسیلےوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Σαλήμ, → سالیم،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700217', l.id, 'سالیم،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὅ → جو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700218', l.id, 'جو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐστιν → ہے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700219', l.id, 'ہے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- βασιλεὺς → باسیلےوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700220', l.id, 'باسیلےوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἰρήνης; → –سلامتی؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800700221', l.id, '–سلامتی؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

