-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58007026

-- Τοιοῦτος → تویووتوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702601', l.id, 'تویووتوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γὰρ → کیونکہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702602', l.id, 'کیونکہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἡμῖν → ہمیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702603', l.id, 'ہمیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702604', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔπρεπεν → ےپرےپےن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702605', l.id, 'ےپرےپےن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀρχιερεύς, → سردار–کاہن،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702606', l.id, 'سردار–کاہن،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὅσιος, → وسیوس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702607', l.id, 'وسیوس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἄκακος, → اکاکوس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702608', l.id, 'اکاکوس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀμίαντος, → امیانتوس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702609', l.id, 'امیانتوس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κεχωρισμένος → کےخوریسمےنوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702610', l.id, 'کےخوریسمےنوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀπὸ → سے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702611', l.id, 'سے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῶν → –کے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702612', l.id, '–کے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἁμαρτωλῶν, → امارتولون،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702613', l.id, 'امارتولون،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702614', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὑψηλότερος → وپسیلوتےروس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702615', l.id, 'وپسیلوتےروس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῶν → –کے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702616', l.id, '–کے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὐρανῶν → –آسمانوں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702617', l.id, '–آسمانوں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γενόμενος; → ہو–کر؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702618', l.id, 'ہو–کر؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

