-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58007022

-- κατὰ → مطابق
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702201', l.id, 'مطابق', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοσοῦτο → توسووتو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702202', l.id, 'توسووتو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702203', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κρείττονος → –بہتر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702204', l.id, '–بہتر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- διαθήκης, → –عہد،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702205', l.id, '–عہد،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γέγονεν → گےگونےن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702206', l.id, 'گےگونےن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔγγυος → ےگگووس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702207', l.id, 'ےگگووس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Ἰησοῦς. → یسوع۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800702208', l.id, 'یسوع۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

