-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58008013

-- ἐν → میں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800801301', l.id, 'میں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῷ → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800801302', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- λέγειν, → لےگےین،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800801303', l.id, 'لےگےین،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Καινὴν, → کاینین،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800801304', l.id, 'کاینین،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πεπαλαίωκεν → پےپالایوکےن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800801305', l.id, 'پےپالایوکےن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὴν → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800801306', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πρώτην; → پہلی؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800801307', l.id, 'پہلی؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὸ → –یہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800801308', l.id, '–یہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δὲ → مگر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800801309', l.id, 'مگر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- παλαιούμενον → پالایوومےنون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800801310', l.id, 'پالایوومےنون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800801311', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γηράσκον, → گیراسکون،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800801312', l.id, 'گیراسکون،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐγγὺς → ےگگوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800801313', l.id, 'ےگگوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀφανισμοῦ. → افانیسموو۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800801314', l.id, 'افانیسموو۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

