-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58008006

-- νυνὶ → نونی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800601', l.id, 'نونی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δὲ, → مگر،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800602', l.id, 'مگر،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- διαφορωτέρας → دیافوروتےراس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800603', l.id, 'دیافوروتےراس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τέτυχεν → تےتوخےن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800604', l.id, 'تےتوخےن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- λειτουργίας, → لےیتوورگیاس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800605', l.id, 'لےیتوورگیاس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὅσῳ → وس–
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800606', l.id, 'وس–', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800607', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κρείττονός → کرےیتتونوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800608', l.id, 'کرےیتتونوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐστιν → ہے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800609', l.id, 'ہے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- διαθήκης → –عہد
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800610', l.id, '–عہد', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μεσίτης, → مےسیتیس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800611', l.id, 'مےسیتیس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἥτις → یتیس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800612', l.id, 'یتیس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐπὶ → پر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800613', l.id, 'پر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κρείττοσιν → بہتر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800614', l.id, 'بہتر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐπαγγελίαις → ےپاگگےلیایس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800615', l.id, 'ےپاگگےلیایس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- νενομοθέτηται. → نےنوموثےتیتای۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800616', l.id, 'نےنوموثےتیتای۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

