-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58008005

-- οἵτινες → ویتینےس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800501', l.id, 'ویتینےس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὑποδείγματι → وپودےیگماتی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800502', l.id, 'وپودےیگماتی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800503', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- σκιᾷ → سکیا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800504', l.id, 'سکیا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- λατρεύουσιν → لاترےوووسین
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800505', l.id, 'لاترےوووسین', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῶν → –کے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800506', l.id, '–کے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐπουρανίων, → ےپوورانیون،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800507', l.id, 'ےپوورانیون،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καθὼς → کاثوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800508', l.id, 'کاثوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κεχρημάτισται → کےخریماتیستای
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800509', l.id, 'کےخریماتیستای', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Μωϋσῆς, → موسیٰ،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800510', l.id, 'موسیٰ،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μέλλων → مےللون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800511', l.id, 'مےللون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐπιτελεῖν → ےپیتےلےین
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800512', l.id, 'ےپیتےلےین', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὴν → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800513', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- σκηνήν; → خیمہ؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800514', l.id, 'خیمہ؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Ὅρα, → ورا،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800515', l.id, 'ورا،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γάρ → کیونکہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800516', l.id, 'کیونکہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- φησίν, → فیسین،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800517', l.id, 'فیسین،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ποιήσεις → پوییسےیس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800518', l.id, 'پوییسےیس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πάντα → سب
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800519', l.id, 'سب', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κατὰ → مطابق
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800520', l.id, 'مطابق', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὸν → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800521', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τύπον → توپون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800522', l.id, 'توپون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὸν → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800523', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δειχθέντα → دےیخثےنتا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800524', l.id, 'دےیخثےنتا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- σοι → سوی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800525', l.id, 'سوی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐν → میں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800526', l.id, 'میں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῷ → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800527', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὄρει. → ورےی۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800800528', l.id, 'ورےی۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

