-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58009025

-- οὐδ’ → وود’
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902501', l.id, 'وود’', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἵνα → تاکہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902502', l.id, 'تاکہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πολλάκις → پوللاکیس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902503', l.id, 'پوللاکیس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- προσφέρῃ → پروسفےر–
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902504', l.id, 'پروسفےر–', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἑαυτόν, → ےاوتون،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902505', l.id, 'ےاوتون،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὥσπερ → جس–طرح
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902506', l.id, 'جس–طرح', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὁ → –یہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902507', l.id, '–یہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀρχιερεὺς → ارخیےرےوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902508', l.id, 'ارخیےرےوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἰσέρχεται → ےیسےرخےتای
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902509', l.id, 'ےیسےرخےتای', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἰς → کے–لیے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902510', l.id, 'کے–لیے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὰ → –یہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902511', l.id, '–یہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἅγια → مقدس–مقام
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902512', l.id, 'مقدس–مقام', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κατ’ → کات’
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902513', l.id, 'کات’', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐνιαυτὸν, → ےنیاوتون،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902514', l.id, 'ےنیاوتون،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐν → میں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902515', l.id, 'میں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αἵματι → –خون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902516', l.id, '–خون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀλλοτρίῳ; → اللوتری–؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902517', l.id, 'اللوتری–؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

