-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58009027

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902701', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καθ’ → کاث’
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902702', l.id, 'کاث’', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὅσον → وسون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902703', l.id, 'وسون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀπόκειται → اپوکےیتای
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902704', l.id, 'اپوکےیتای', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοῖς → –اُن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902705', l.id, '–اُن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀνθρώποις → انثروپویس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902706', l.id, 'انثروپویس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἅπαξ → اپاکس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902707', l.id, 'اپاکس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀποθανεῖν, → مرنا،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902708', l.id, 'مرنا،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μετὰ → ساتھ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902709', l.id, 'ساتھ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δὲ → مگر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902710', l.id, 'مگر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοῦτο, → یہ،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902711', l.id, 'یہ،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κρίσις; → کریسیس؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5800902712', l.id, 'کریسیس؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

