-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58010007

-- τότε → تب
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000701', l.id, 'تب', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἶπον, → ےیپون،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000702', l.id, 'ےیپون،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Ἰδοὺ, → یدوو،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000703', l.id, 'یدوو،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἥκω --  → یکو -- 
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000704', l.id, 'یکو -- ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐν → میں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000705', l.id, 'میں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κεφαλίδι → کےفالیدی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000706', l.id, 'کےفالیدی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- βιβλίου → بیبلیوو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000707', l.id, 'بیبلیوو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γέγραπται → گےگراپتای
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000708', l.id, 'گےگراپتای', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- περὶ → بارے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000709', l.id, 'بارے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐμοῦ --  → ےموو -- 
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000710', l.id, 'ےموو -- ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοῦ → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000711', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ποιῆσαι, → پوییسای،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000712', l.id, 'پوییسای،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὁ → –یہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000713', l.id, '–یہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Θεός, → خدا،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000714', l.id, 'خدا،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὸ → –یہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000715', l.id, '–یہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- θέλημά → ثےلیما
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000716', l.id, 'ثےلیما', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- σου. → تیرا۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000717', l.id, 'تیرا۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

