-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58010002

-- ἐπεὶ → ےپےی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000201', l.id, 'ےپےی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὐκ → نہیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000202', l.id, 'نہیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἂν → ان
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000203', l.id, 'ان', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐπαύσαντο → ےپاوسانتو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000204', l.id, 'ےپاوسانتو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- προσφερόμεναι, → پروسفےرومےنای،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000205', l.id, 'پروسفےرومےنای،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- διὰ → ذریعے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000206', l.id, 'ذریعے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὸ → –یہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000207', l.id, '–یہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μηδεμίαν → میدےمیان
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000208', l.id, 'میدےمیان', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔχειν → رکھنا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000209', l.id, 'رکھنا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔτι → ابھی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000210', l.id, 'ابھی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- συνείδησιν → سونےیدیسین
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000211', l.id, 'سونےیدیسین', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἁμαρτιῶν, → –گناہوں،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000212', l.id, '–گناہوں،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοὺς → –اُن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000213', l.id, '–اُن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- λατρεύοντας → لاترےوونتاس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000214', l.id, 'لاترےوونتاس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἅπαξ → اپاکس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000215', l.id, 'اپاکس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κεκαθαρισμένους? → کےکاثاریسمےنووس؟
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000216', l.id, 'کےکاثاریسمےنووس؟', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

