-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58010039

-- ἡμεῖς → ہم
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801003901', l.id, 'ہم', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δὲ → مگر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801003902', l.id, 'مگر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὐκ → نہیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801003903', l.id, 'نہیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐσμὲν → ےسمےن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801003904', l.id, 'ےسمےن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὑποστολῆς → وپوستولیس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801003905', l.id, 'وپوستولیس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἰς → کے–لیے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801003906', l.id, 'کے–لیے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀπώλειαν, → اپولےیان،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801003907', l.id, 'اپولےیان،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀλλὰ → بلکہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801003908', l.id, 'بلکہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πίστεως → –ایمان
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801003909', l.id, '–ایمان', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἰς → کے–لیے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801003910', l.id, 'کے–لیے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- περιποίησιν → پےریپوییسین
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801003911', l.id, 'پےریپوییسین', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ψυχῆς. → پسوخیس۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801003912', l.id, 'پسوخیس۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

