-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58010003

-- ἀλλ’ → الل’
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000301', l.id, 'الل’', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐν → میں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000302', l.id, 'میں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αὐταῖς, → اُن–کو،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000303', l.id, 'اُن–کو،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀνάμνησις → انامنیسیس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000304', l.id, 'انامنیسیس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἁμαρτιῶν → –گناہوں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000305', l.id, '–گناہوں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κατ’ → کات’
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000306', l.id, 'کات’', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐνιαυτόν. → ےنیاوتون۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000307', l.id, 'ےنیاوتون۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

