-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58010006

-- ὁλοκαυτώματα → سوختنی–قربانیاں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000601', l.id, 'سوختنی–قربانیاں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000602', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- περὶ → بارے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000603', l.id, 'بارے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἁμαρτίας → –گناہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000604', l.id, '–گناہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὐκ → نہیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000605', l.id, 'نہیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εὐδόκησας. → ےودوکیساس۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801000606', l.id, 'ےودوکیساس۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

