-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58011039

-- Καὶ → کای
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801103901', l.id, 'کای', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὗτοι → ووتوی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801103902', l.id, 'ووتوی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πάντες, → سب،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801103903', l.id, 'سب،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μαρτυρηθέντες → مارتوریثےنتےس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801103904', l.id, 'مارتوریثےنتےس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- διὰ → ذریعے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801103905', l.id, 'ذریعے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῆς → –کی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801103906', l.id, '–کی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πίστεως, → –ایمان،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801103907', l.id, '–ایمان،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὐκ → نہیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801103908', l.id, 'نہیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐκομίσαντο → ےکومیسانتو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801103909', l.id, 'ےکومیسانتو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὴν → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801103910', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐπαγγελίαν; → وعدہ؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801103911', l.id, 'وعدہ؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

