-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58011011

-- Πίστει → پیستےی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101101', l.id, 'پیستےی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ, → اور،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101102', l.id, 'اور،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αὐτῇ → اُسے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101103', l.id, 'اُسے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Σάρρᾳ → سارر–
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101104', l.id, 'سارر–', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- [στεῖρα], → [ستےیرا]،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101105', l.id, '[ستےیرا]،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δύναμιν → قدرت
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101106', l.id, 'قدرت', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἰς → کے–لیے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101107', l.id, 'کے–لیے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καταβολὴν → کاتابولین
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101108', l.id, 'کاتابولین', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- σπέρματος → سپےرماتوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101109', l.id, 'سپےرماتوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔλαβεν, → لیا،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101110', l.id, 'لیا،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101111', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- παρὰ → سے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101112', l.id, 'سے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καιρὸν → کایرون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101113', l.id, 'کایرون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἡλικίας, → یلیکیاس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101114', l.id, 'یلیکیاس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐπεὶ → ےپےی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101115', l.id, 'ےپےی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πιστὸν → پیستون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101116', l.id, 'پیستون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἡγήσατο → یگیساتو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101117', l.id, 'یگیساتو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὸν → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101118', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐπαγγειλάμενον. → ےپاگگےیلامےنون۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101119', l.id, 'ےپاگگےیلامےنون۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

