-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58011007

-- Πίστει → پیستےی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100701', l.id, 'پیستےی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- χρηματισθεὶς, → خریماتیسثےیس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100702', l.id, 'خریماتیسثےیس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Νῶε → نوح
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100703', l.id, 'نوح', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- περὶ → بارے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100704', l.id, 'بارے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῶν → –کے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100705', l.id, '–کے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μηδέπω → میدےپو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100706', l.id, 'میدےپو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- βλεπομένων, → بلےپومےنون،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100707', l.id, 'بلےپومےنون،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εὐλαβηθεὶς, → ےولابیثےیس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100708', l.id, 'ےولابیثےیس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κατεσκεύασεν → کاتےسکےواسےن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100709', l.id, 'کاتےسکےواسےن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κιβωτὸν → کیبوتون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100710', l.id, 'کیبوتون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἰς → کے–لیے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100711', l.id, 'کے–لیے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- σωτηρίαν → نجات
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100712', l.id, 'نجات', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοῦ → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100713', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οἴκου → ویکوو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100714', l.id, 'ویکوو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αὐτοῦ; → اُس–کا؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100715', l.id, 'اُس–کا؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δι’ → دی’
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100716', l.id, 'دی’', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἧς → جس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100717', l.id, 'جس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κατέκρινεν → کاتےکرینےن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100718', l.id, 'کاتےکرینےن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὸν → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100719', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κόσμον, → کوسمون،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100720', l.id, 'کوسمون،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100721', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῆς → –کی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100722', l.id, '–کی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κατὰ → مطابق
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100723', l.id, 'مطابق', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πίστιν → ایمان
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100724', l.id, 'ایمان', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δικαιοσύνης, → –راستبازی،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100725', l.id, '–راستبازی،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐγένετο → ہوا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100726', l.id, 'ہوا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κληρονόμος. → وارث۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100727', l.id, 'وارث۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

