-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58011014

-- οἱ → –وہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101401', l.id, '–وہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γὰρ → کیونکہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101402', l.id, 'کیونکہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοιαῦτα → تویاوتا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101403', l.id, 'تویاوتا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- λέγοντες, → لےگونتےس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101404', l.id, 'لےگونتےس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐμφανίζουσιν → ےمفانیزووسین
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101405', l.id, 'ےمفانیزووسین', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὅτι → کہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101406', l.id, 'کہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πατρίδα → پاتریدا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101407', l.id, 'پاتریدا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐπιζητοῦσιν. → ےپیزیتووسین۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101408', l.id, 'ےپیزیتووسین۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

