-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58011004

-- Πίστει → پیستےی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100401', l.id, 'پیستےی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πλείονα → پلےیونا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100402', l.id, 'پلےیونا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- θυσίαν, → قربانی،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100403', l.id, 'قربانی،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Ἅβελ → ہابیل
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100404', l.id, 'ہابیل', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- παρὰ → سے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100405', l.id, 'سے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Κάϊν → کاین
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100406', l.id, 'کاین', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- προσήνεγκεν → پروسینےگکےن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100407', l.id, 'پروسینےگکےن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῷ → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100408', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Θεῷ; → خدا؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100409', l.id, 'خدا؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δι’ → دی’
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100410', l.id, 'دی’', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἧς → جس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100411', l.id, 'جس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐμαρτυρήθη → ےمارتوریثی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100412', l.id, 'ےمارتوریثی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἶναι → ہونا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100413', l.id, 'ہونا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δίκαιος, → راستباز،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100414', l.id, 'راستباز،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μαρτυροῦντος → مارتوروونتوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100415', l.id, 'مارتوروونتوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐπὶ → پر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100416', l.id, 'پر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοῖς → –اُن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100417', l.id, '–اُن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δώροις → دورویس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100418', l.id, 'دورویس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αὐτοῦ → اُس–کا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100419', l.id, 'اُس–کا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοῦ → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100420', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Θεοῦ; → –خدا؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100421', l.id, '–خدا؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100422', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δι’ → دی’
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100423', l.id, 'دی’', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αὐτῆς, → اُس–کی،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100424', l.id, 'اُس–کی،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀποθανὼν, → اپوثانون،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100425', l.id, 'اپوثانون،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔτι → ابھی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100426', l.id, 'ابھی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- λαλεῖ. → بولتا–ہے۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801100427', l.id, 'بولتا–ہے۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

