-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58011040

-- τοῦ → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801104001', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Θεοῦ → –خدا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801104002', l.id, '–خدا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- περὶ → بارے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801104003', l.id, 'بارے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἡμῶν → ہمارے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801104004', l.id, 'ہمارے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κρεῖττόν → کرےیتتون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801104005', l.id, 'کرےیتتون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τι → تی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801104006', l.id, 'تی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- προβλεψαμένου, → پروبلےپسامےنوو،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801104007', l.id, 'پروبلےپسامےنوو،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἵνα → تاکہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801104008', l.id, 'تاکہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μὴ → نہیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801104009', l.id, 'نہیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- χωρὶς → بغیر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801104010', l.id, 'بغیر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἡμῶν → ہمارے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801104011', l.id, 'ہمارے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τελειωθῶσιν. → تےلےیوثوسین۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801104012', l.id, 'تےلےیوثوسین۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

