-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58011013

-- Κατὰ → کاتا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101301', l.id, 'کاتا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πίστιν → ایمان
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101302', l.id, 'ایمان', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀπέθανον → اپےثانون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101303', l.id, 'اپےثانون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὗτοι → ووتوی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101304', l.id, 'ووتوی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πάντες, → سب،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101305', l.id, 'سب،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μὴ → نہیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101306', l.id, 'نہیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κομισάμενοι → کومیسامےنوی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101307', l.id, 'کومیسامےنوی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὰς → –اُن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101308', l.id, '–اُن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐπαγγελίας, → –وعدے،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101309', l.id, '–وعدے،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀλλὰ → بلکہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101310', l.id, 'بلکہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πόρρωθεν → پورروثےن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101311', l.id, 'پورروثےن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αὐτὰς → اوتاس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101312', l.id, 'اوتاس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἰδόντες, → یدونتےس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101313', l.id, 'یدونتےس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101314', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀσπασάμενοι, → اسپاسامےنوی،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101315', l.id, 'اسپاسامےنوی،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101316', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὁμολογήσαντες → ومولوگیسانتےس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101317', l.id, 'ومولوگیسانتےس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὅτι → کہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101318', l.id, 'کہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ξένοι → کسےنوی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101319', l.id, 'کسےنوی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101320', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- παρεπίδημοί → پارےپیدیموی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101321', l.id, 'پارےپیدیموی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἰσιν → ےیسین
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101322', l.id, 'ےیسین', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐπὶ → پر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101323', l.id, 'پر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῆς → –کی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101324', l.id, '–کی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γῆς. → –زمین۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801101325', l.id, '–زمین۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

