-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58011024

-- Πίστει → پیستےی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801102401', l.id, 'پیستےی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Μωϋσῆς, → موسیٰ،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801102402', l.id, 'موسیٰ،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μέγας → بڑا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801102403', l.id, 'بڑا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γενόμενος, → ہو–کر،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801102404', l.id, 'ہو–کر،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἠρνήσατο → یرنیساتو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801102405', l.id, 'یرنیساتو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- λέγεσθαι → لےگےسثای
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801102406', l.id, 'لےگےسثای', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- υἱὸς → ویوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801102407', l.id, 'ویوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- θυγατρὸς → ثوگاتروس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801102408', l.id, 'ثوگاتروس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Φαραώ; → فاراو؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801102409', l.id, 'فاراو؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

