-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58012016

-- μή → نہیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201601', l.id, 'نہیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τις → کوئی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201602', l.id, 'کوئی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πόρνος → پورنوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201603', l.id, 'پورنوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἢ → ی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201604', l.id, 'ی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- βέβηλος, → بےبیلوس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201605', l.id, 'بےبیلوس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὡς → جیسے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201606', l.id, 'جیسے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Ἠσαῦ, → یساو،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201607', l.id, 'یساو،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὃς → جو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201608', l.id, 'جو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀντὶ → انتی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201609', l.id, 'انتی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- βρώσεως → بروسےوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201610', l.id, 'بروسےوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μιᾶς, → میاس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201611', l.id, 'میاس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀπέδετο → اپےدےتو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201612', l.id, 'اپےدےتو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὰ → –یہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201613', l.id, '–یہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πρωτοτόκια → پروتوتوکیا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201614', l.id, 'پروتوتوکیا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἑαυτοῦ. → ےاوتوو۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201615', l.id, 'ےاوتوو۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

