-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58012003

-- ἀναλογίσασθε → انالوگیساسثے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200301', l.id, 'انالوگیساسثے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γὰρ, → کیونکہ،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200302', l.id, 'کیونکہ،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὸν → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200303', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοιαύτην → تویاوتین
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200304', l.id, 'تویاوتین', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὑπομεμενηκότα → وپومےمےنیکوتا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200305', l.id, 'وپومےمےنیکوتا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὑπὸ → سے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200306', l.id, 'سے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῶν → –کے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200307', l.id, '–کے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἁμαρτωλῶν → امارتولون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200308', l.id, 'امارتولون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἰς → کے–لیے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200309', l.id, 'کے–لیے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἑαυτὸν → ےاوتون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200310', l.id, 'ےاوتون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀντιλογίαν, → انتیلوگیان،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200311', l.id, 'انتیلوگیان،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἵνα → تاکہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200312', l.id, 'تاکہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μὴ → نہیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200313', l.id, 'نہیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κάμητε, → کامیتے،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200314', l.id, 'کامیتے،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ταῖς → تایس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200315', l.id, 'تایس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ψυχαῖς → پسوخایس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200316', l.id, 'پسوخایس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὑμῶν → تمہارے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200317', l.id, 'تمہارے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐκλυόμενοι. → ےکلوومےنوی۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200318', l.id, 'ےکلوومےنوی۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

