-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58012025

-- Βλέπετε → بلےپےتے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202501', l.id, 'بلےپےتے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μὴ → نہیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202502', l.id, 'نہیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- παραιτήσησθε → پارایتیسیسثے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202503', l.id, 'پارایتیسیسثے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὸν → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202504', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- λαλοῦντα. → لالوونتا۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202505', l.id, 'لالوونتا۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἰ → اگر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202506', l.id, 'اگر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γὰρ → کیونکہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202507', l.id, 'کیونکہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐκεῖνοι → ےکےینوی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202508', l.id, 'ےکےینوی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὐκ → نہیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202509', l.id, 'نہیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐξέφυγον, → ےکسےفوگون،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202510', l.id, 'ےکسےفوگون،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐπὶ → پر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202511', l.id, 'پر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γῆς → –زمین
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202512', l.id, '–زمین', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- παραιτησάμενοι → پارایتیسامےنوی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202513', l.id, 'پارایتیسامےنوی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὸν → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202514', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- χρηματίζοντα, → خریماتیزونتا،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202515', l.id, 'خریماتیزونتا،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πολὺ → پولو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202516', l.id, 'پولو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μᾶλλον → زیادہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202517', l.id, 'زیادہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἡμεῖς → ہم
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202518', l.id, 'ہم', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οἱ → –وہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202519', l.id, '–وہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὸν → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202520', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀπ’ → اپ’
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202521', l.id, 'اپ’', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὐρανῶν → –آسمانوں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202522', l.id, '–آسمانوں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀποστρεφόμενοι, → اپوسترےفومےنوی،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202523', l.id, 'اپوسترےفومےنوی،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

