-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58012021

-- καί, → اور،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202101', l.id, 'اور،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὕτω → اِسی–طرح
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202102', l.id, 'اِسی–طرح', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- φοβερὸν → فوبےرون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202103', l.id, 'فوبےرون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἦν → تھا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202104', l.id, 'تھا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὸ → –یہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202105', l.id, '–یہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- φανταζόμενον → فانتازومےنون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202106', l.id, 'فانتازومےنون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Μωϋσῆς → موسیٰ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202107', l.id, 'موسیٰ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἶπεν, → کہا،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202108', l.id, 'کہا،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Ἔκφοβός → ےکفوبوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202109', l.id, 'ےکفوبوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἰμι, → ےیمی،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202110', l.id, 'ےیمی،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202111', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔντρομος. → ےنتروموس۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801202112', l.id, 'ےنتروموس۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

