-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58012013

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201301', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τροχιὰς → تروخیاس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201302', l.id, 'تروخیاس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὀρθὰς → ورثاس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201303', l.id, 'ورثاس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ποιεῖτε → پویےیتے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201304', l.id, 'پویےیتے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοῖς → –اُن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201305', l.id, '–اُن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ποσὶν → پوسین
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201306', l.id, 'پوسین', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὑμῶν, → تمہارے،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201307', l.id, 'تمہارے،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἵνα → تاکہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201308', l.id, 'تاکہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μὴ → نہیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201309', l.id, 'نہیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὸ → –یہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201310', l.id, '–یہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- χωλὸν → خولون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201311', l.id, 'خولون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐκτραπῇ; → ےکتراپی؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201312', l.id, 'ےکتراپی؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἰαθῇ → یاثی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201313', l.id, 'یاثی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δὲ → مگر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201314', l.id, 'مگر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μᾶλλον. → زیادہ۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201315', l.id, 'زیادہ۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

