-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58012017

-- ἴστε → یستے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201701', l.id, 'یستے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γὰρ → کیونکہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201702', l.id, 'کیونکہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὅτι → کہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201703', l.id, 'کہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201704', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μετέπειτα, → مےتےپےیتا،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201705', l.id, 'مےتےپےیتا،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- θέλων → ثےلون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201706', l.id, 'ثےلون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- κληρονομῆσαι → کلیرونومیسای
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201707', l.id, 'کلیرونومیسای', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὴν → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201708', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εὐλογίαν, → ےولوگیان،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201709', l.id, 'ےولوگیان،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀπεδοκιμάσθη; → اپےدوکیماسثی؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201710', l.id, 'اپےدوکیماسثی؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μετανοίας → مےتانویاس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201711', l.id, 'مےتانویاس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- γὰρ → کیونکہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201712', l.id, 'کیونکہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τόπον → توپون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201713', l.id, 'توپون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὐχ → نہیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201714', l.id, 'نہیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εὗρεν, → ےورےن،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201715', l.id, 'ےورےن،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καίπερ → کایپےر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201716', l.id, 'کایپےر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μετὰ → ساتھ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201717', l.id, 'ساتھ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- δακρύων → داکروون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201718', l.id, 'داکروون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐκζητήσας → ےکزیتیساس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201719', l.id, 'ےکزیتیساس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αὐτήν. → اُسے۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801201720', l.id, 'اُسے۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

