-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58012009

-- εἶτα → ےیتا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200901', l.id, 'ےیتا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοὺς → –اُن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200902', l.id, '–اُن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μὲν → مےن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200903', l.id, 'مےن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῆς → –کی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200904', l.id, '–کی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- σαρκὸς → سارکوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200905', l.id, 'سارکوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἡμῶν → ہمارے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200906', l.id, 'ہمارے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πατέρας → پاتےراس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200907', l.id, 'پاتےراس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- εἴχομεν → ےیخومےن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200908', l.id, 'ےیخومےن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- παιδευτὰς, → پایدےوتاس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200909', l.id, 'پایدےوتاس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200910', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐνετρεπόμεθα; → ےنےترےپومےثا؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200911', l.id, 'ےنےترےپومےثا؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὐ → نہیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200912', l.id, 'نہیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πολὺ → پولو
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200913', l.id, 'پولو', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- [δὲ] → [دے]
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200914', l.id, '[دے]', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μᾶλλον, → زیادہ،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200915', l.id, 'زیادہ،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὑποταγησόμεθα → وپوتاگیسومےثا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200916', l.id, 'وپوتاگیسومےثا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῷ → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200917', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Πατρὶ → پاتری
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200918', l.id, 'پاتری', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῶν → –کے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200919', l.id, '–کے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πνευμάτων, → پنےوماتون،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200920', l.id, 'پنےوماتون،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καὶ → اور
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200921', l.id, 'اور', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ζήσομεν? → زیسومےن؟
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801200922', l.id, 'زیسومےن؟', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

