-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58013015

-- δι’ → دی’
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301501', l.id, 'دی’', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αὐτοῦ → اُس–کا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301502', l.id, 'اُس–کا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὖν → پس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301503', l.id, 'پس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἀναφέρωμεν → انافےرومےن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301504', l.id, 'انافےرومےن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- θυσίαν → قربانی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301505', l.id, 'قربانی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αἰνέσεως → اینےسےوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301506', l.id, 'اینےسےوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- διὰ → ذریعے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301507', l.id, 'ذریعے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- παντὸς → پانتوس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301508', l.id, 'پانتوس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῷ → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301509', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- Θεῷ, → خدا،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301510', l.id, 'خدا،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τοῦτ’ → تووت’
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301511', l.id, 'تووت’', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔστιν, → ہے،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301512', l.id, 'ہے،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- καρπὸν → کارپون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301513', l.id, 'کارپون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- χειλέων → خےیلےون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301514', l.id, 'خےیلےون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὁμολογούντων → ومولوگوونتون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301515', l.id, 'ومولوگوونتون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῷ → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301516', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὀνόματι → ونوماتی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301517', l.id, 'ونوماتی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αὐτοῦ. → اُس–کا۔
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301518', l.id, 'اُس–کا۔', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

