-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58013013

-- τοίνυν → توینون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301301', l.id, 'توینون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐξερχώμεθα → ےکسےرخومےثا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301302', l.id, 'ےکسےرخومےثا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- πρὸς → کے–لیے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301303', l.id, 'کے–لیے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αὐτὸν, → اوتون،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301304', l.id, 'اوتون،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔξω → باہر
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301305', l.id, 'باہر', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῆς → –کی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301306', l.id, '–کی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- παρεμβολῆς, → پارےمبولیس،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301307', l.id, 'پارےمبولیس،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τὸν → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301308', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ὀνειδισμὸν → ونےیدیسمون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301309', l.id, 'ونےیدیسمون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- αὐτοῦ → اُس–کا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301310', l.id, 'اُس–کا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- φέροντες; → فےرونتےس؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301311', l.id, 'فےرونتےس؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

