-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58013001

-- Ἡ → ی
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801300101', l.id, 'ی', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- φιλαδελφία → فیلادےلفیا
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801300102', l.id, 'فیلادےلفیا', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- μενέτω; → مےنےتو؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801300103', l.id, 'مےنےتو؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

