-- For God so loved the world, that He gave His only begotten Son,
-- that all who believe in Him should not perish but have everlasting life.
-- — John 3:16

-- Urdu (urd) translation for hebrews
-- Generated by opus-4.5-chirho

-- Verse 58013010

-- Ἔχομεν → ےخومےن
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301001', l.id, 'ےخومےن', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- θυσιαστήριον → ثوسیاستیریون
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301002', l.id, 'ثوسیاستیریون', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐξ → سے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301003', l.id, 'سے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὗ → جس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301004', l.id, 'جس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- φαγεῖν, → فاگےین،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301005', l.id, 'فاگےین،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οὐκ → نہیں
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301006', l.id, 'نہیں', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἔχουσιν → ےخووسین
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301007', l.id, 'ےخووسین', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- ἐξουσίαν, → ےکسووسیان،
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301008', l.id, 'ےکسووسیان،', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- οἱ → –وہ
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301009', l.id, '–وہ', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- τῇ → –اُس
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301010', l.id, '–اُس', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- σκηνῇ → –خیمے
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301011', l.id, '–خیمے', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

-- λατρεύοντες; → لاترےوونتےس؛
INSERT INTO machine_gloss (word_id, language_id, gloss, source)
SELECT '5801301012', l.id, 'لاترےوونتےس؛', 'opus-4.5-chirho'
FROM language l WHERE l.code = 'urd'
ON CONFLICT (word_id, language_id) DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;

